spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8084/
          predicates:
            - Path=/command/room/**
        - id: r2
          uri: http://localhost:8083/
          predicates:
            - Path=/query/room/**
  application:
    name: gateway-service
server:
  port: 8888
